import { Header } from "@/components/landing/header";
import { Footer } from "@/components/landing/footer";
import { ParticleBackground } from "@/components/landing/particle-background";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";

const faqs = [
  {
    question: "What is Scientisto?",
    answer: "Scientisto is an AI-powered research and content creation assistant. You provide a prompt, and our AI generates a comprehensive, well-structured document like a research paper, PRD, or essay in minutes. You can then export this document as a PDF or DOCX file.",
  },
  {
    question: "How does the AI work?",
    answer: "Scientisto uses advanced large language models (LLMs) from Google. When you enter a prompt, the AI analyzes your request, conducts deep research by synthesizing information from a vast knowledge base, and then structures the findings into your chosen document format. It's designed to understand context, follow structural requirements, and produce high-quality, coherent text.",
  },
  {
    question: "Is the generated content unique and plagiarism-free?",
    answer: "The content is generated by an AI model in real-time and is original in its composition. However, as it synthesizes information from existing public knowledge, it may contain phrases or sentences that are similar to other sources. We always recommend users review and edit the generated content, and use plagiarism checkers if they are submitting the work for academic or professional purposes.",
  },
  {
    question: "Who owns the content I generate?",
    answer: "You, the user, retain ownership of the prompts you provide and the final documents you generate. You are free to use them for personal, academic, or commercial purposes, in accordance with our Terms of Service.",
  },
  {
    question: "How is my data and privacy handled?",
    answer: "We take privacy seriously. Your prompts and generated documents are stored securely and are tied to your account. We do not share your personal data or generated content with third parties. For more details, please review our Privacy Policy.",
  },
  {
    question: "What are the upcoming features?",
    answer: "We are constantly working to expand Scientisto's capabilities! We are currently developing creative tools like a Story Generator, Comic Generator, and even a Manga & Anime Generator to turn your text prompts into visual stories. Stay tuned for updates!",
  },
  {
    question: "Is there a free trial?",
    answer: "Yes! Scientisto offers a free 'Explorer' plan that allows you to generate a limited number of documents each month so you can experience the power of our AI firsthand. You can sign up for free to get started.",
  },
];

export default function FaqPage() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <Header />
      <main className="flex-1">
        <section className="relative container mx-auto text-center py-16 sm:py-24 overflow-hidden">
          <ParticleBackground />
          <div className="relative z-10 animate-fade-in-up">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold font-headline tracking-tighter">
              Frequently Asked Questions
            </h1>
            <p className="mt-4 max-w-2xl mx-auto text-lg text-muted-foreground">
              Have questions? We have answers. If you can't find what you're looking for, feel free to contact us.
            </p>
          </div>
        </section>

        <section className="container mx-auto pb-16 sm:pb-24">
          <Card className="max-w-4xl mx-auto bg-card/50">
            <CardContent className="p-6 sm:p-8">
              <Accordion type="single" collapsible className="w-full">
                {faqs.map((faq, index) => (
                  <AccordionItem key={index} value={`item-${index}`}>
                    <AccordionTrigger className="text-left text-lg font-semibold hover:no-underline">{faq.question}</AccordionTrigger>
                    <AccordionContent className="text-base text-muted-foreground pt-2">
                      {faq.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </CardContent>
          </Card>
        </section>
      </main>
      <Footer />
    </div>
  );
}
